### ISSUE TITLE
Generate and link to data files 

### ISSUE THREAD

**Issue by mattt** [NSHipster/XcodeBuildSettings.com#10]
Build settings should be made available in common, convenient formats like JSON and CSV.

**Comment by mrosales** [comment]
The latest source code does generate the JSON and CSV versions, but the seem not to be public on the site. Running the script to produce this locally gives me a valid json file at the expected path, but it doesn't seem to be live.

https://xcodebuildsettings.com/data/build_settings.json

Does not resolve for me.

Running this locally works:

```
bundle install
bundle exec rake data
bundle exec jekyll serve

curl http://localhost:4000/data/build_settings.json
```

**Comment by mattt** [comment]
You're right — I need to add a hook / route in Jekyll to expose those files in the final build. That should be pretty easy to do — let me take a look now.

**Comment by mattt** [comment]
@mrosales This is now resolved. See https://xcodebuildsettings.com/build_settings.csv. Thanks for pointing this out!
