### ISSUE TITLE
Missing: ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME

### ISSUE THREAD

**Issue by MKGitHub** [NSHipster/XcodeBuildSettings.com#24]
Xcode 12 added the new ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME setting, it is missing here.

**Comment by mattt** [comment]
This has since been added to the site. See: https://xcodebuildsettings.com/#assetcatalog_compiler_global_accent_color_name
