### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by amomchilov** [NSHipster/XcodeBuildSettings.com#34]
FYI https://www.isitdownrightnow.com/xcodebuildsettings.com.html

Looks like a DNS failure

**Comment by Kristine1975** [comment]
In the meantime, you can use the archived site: https://web.archive.org/web/20210301125243/https://xcodebuildsettings.com/ (searching works, as it's done in the browser)

**Comment by awaisiosdev** [comment]
can we do something to bring it back online ?

**Comment by mattt** [comment]
XcodeBuildSettings.com is back online. Apologies for the service disruption.
